# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TherapyTrak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TherapyTrak
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn'

  target 'TherapyTrakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TherapyTrakUITests' do
    # Pods for testing
  end

end
